/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MenuId = bigint;
export interface MenuItem {
  'id' : MenuId,
  'categoryName' : string,
  'name' : string,
  'isAvailable' : boolean,
  'vendorId' : VendorId,
  'rating' : number,
  'isVeg' : boolean,
  'price' : number,
  'prepTimeMinutes' : bigint,
}
export type OrderId = bigint;
export interface OrderType {
  'id' : OrderId,
  'status' : string,
  'paymentMethod' : string,
  'trainNumber' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'totalAmount' : number,
  'vendorId' : VendorId,
  'discount' : number,
  'ecoPackaging' : boolean,
  'items' : Array<
    { 'quantity' : bigint, 'price' : number, 'menuItemId' : string }
  >,
  'seatNumber' : string,
  'subtotal' : number,
  'coachNumber' : string,
  'platformNumber' : string,
}
export type Phone = string;
export interface User {
  'id' : UserId,
  'referralCode' : string,
  'isBNPLEnabled' : boolean,
  'name' : string,
  'pnrHistory' : Array<string>,
  'phone' : Phone,
  'walletCredits' : number,
  'isVerifiedTraveler' : boolean,
  'seatNumber' : string,
  'coachNumber' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : VendorId,
  'name' : string,
  'isActive' : boolean,
  'gateEntry' : string,
  'platformNumber' : string,
}
export type VendorId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCredits' : ActorMethod<[number], undefined>,
  'addMenuItem' : ActorMethod<
    [string, VendorId, string, number, boolean, bigint],
    MenuId
  >,
  'addVendor' : ActorMethod<[string, string, string], VendorId>,
  'applyReferral' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[OrderId], undefined>,
  'deductCredits' : ActorMethod<[number], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderType>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], OrderType>,
  'getOrdersByUser' : ActorMethod<[UserId], Array<OrderType>>,
  'getOrdersByVendor' : ActorMethod<[VendorId], Array<OrderType>>,
  'getPNRHistory' : ActorMethod<[], Array<string>>,
  'getUser' : ActorMethod<[UserId], User>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'listMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'listVendors' : ActorMethod<[], Array<Vendor>>,
  'placeOrder' : ActorMethod<
    [
      UserId,
      VendorId,
      Array<{ 'quantity' : bigint, 'price' : number, 'menuItemId' : string }>,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    OrderId
  >,
  'registerUser' : ActorMethod<[string, Phone], undefined>,
  'storePNR' : ActorMethod<[string], undefined>,
  'toggleItemAvailability' : ActorMethod<[MenuId], undefined>,
  'updateMenuItem' : ActorMethod<
    [MenuId, string, VendorId, string, number, boolean, bigint, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, string], undefined>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
  'updateVendor' : ActorMethod<
    [VendorId, string, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];