/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VendorId = IDL.Nat;
export const MenuId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderType = IDL.Record({
  'id' : OrderId,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'trainNumber' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'vendorId' : VendorId,
  'discount' : IDL.Float64,
  'ecoPackaging' : IDL.Bool,
  'items' : IDL.Vec(
    IDL.Record({
      'quantity' : IDL.Nat,
      'price' : IDL.Float64,
      'menuItemId' : IDL.Text,
    })
  ),
  'seatNumber' : IDL.Text,
  'subtotal' : IDL.Float64,
  'coachNumber' : IDL.Text,
  'platformNumber' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Phone = IDL.Text;
export const User = IDL.Record({
  'id' : UserId,
  'referralCode' : IDL.Text,
  'isBNPLEnabled' : IDL.Bool,
  'name' : IDL.Text,
  'pnrHistory' : IDL.Vec(IDL.Text),
  'phone' : Phone,
  'walletCredits' : IDL.Float64,
  'isVerifiedTraveler' : IDL.Bool,
  'seatNumber' : IDL.Text,
  'coachNumber' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : MenuId,
  'categoryName' : IDL.Text,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'vendorId' : VendorId,
  'rating' : IDL.Float64,
  'isVeg' : IDL.Bool,
  'price' : IDL.Float64,
  'prepTimeMinutes' : IDL.Nat,
});
export const Vendor = IDL.Record({
  'id' : VendorId,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'gateEntry' : IDL.Text,
  'platformNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCredits' : IDL.Func([IDL.Float64], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Text, VendorId, IDL.Text, IDL.Float64, IDL.Bool, IDL.Nat],
      [MenuId],
      [],
    ),
  'addVendor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [VendorId], []),
  'applyReferral' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([OrderId], [], []),
  'deductCredits' : IDL.Func([IDL.Float64], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([OrderId], [OrderType], ['query']),
  'getOrdersByUser' : IDL.Func([UserId], [IDL.Vec(OrderType)], ['query']),
  'getOrdersByVendor' : IDL.Func([VendorId], [IDL.Vec(OrderType)], ['query']),
  'getPNRHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUser' : IDL.Func([UserId], [User], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'listMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'listVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'placeOrder' : IDL.Func(
      [
        UserId,
        VendorId,
        IDL.Vec(
          IDL.Record({
            'quantity' : IDL.Nat,
            'price' : IDL.Float64,
            'menuItemId' : IDL.Text,
          })
        ),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [OrderId],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text, Phone], [], []),
  'storePNR' : IDL.Func([IDL.Text], [], []),
  'toggleItemAvailability' : IDL.Func([MenuId], [], []),
  'updateMenuItem' : IDL.Func(
      [
        MenuId,
        IDL.Text,
        VendorId,
        IDL.Text,
        IDL.Float64,
        IDL.Bool,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateVendor' : IDL.Func(
      [VendorId, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VendorId = IDL.Nat;
  const MenuId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderType = IDL.Record({
    'id' : OrderId,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'trainNumber' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'vendorId' : VendorId,
    'discount' : IDL.Float64,
    'ecoPackaging' : IDL.Bool,
    'items' : IDL.Vec(
      IDL.Record({
        'quantity' : IDL.Nat,
        'price' : IDL.Float64,
        'menuItemId' : IDL.Text,
      })
    ),
    'seatNumber' : IDL.Text,
    'subtotal' : IDL.Float64,
    'coachNumber' : IDL.Text,
    'platformNumber' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Phone = IDL.Text;
  const User = IDL.Record({
    'id' : UserId,
    'referralCode' : IDL.Text,
    'isBNPLEnabled' : IDL.Bool,
    'name' : IDL.Text,
    'pnrHistory' : IDL.Vec(IDL.Text),
    'phone' : Phone,
    'walletCredits' : IDL.Float64,
    'isVerifiedTraveler' : IDL.Bool,
    'seatNumber' : IDL.Text,
    'coachNumber' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : MenuId,
    'categoryName' : IDL.Text,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'vendorId' : VendorId,
    'rating' : IDL.Float64,
    'isVeg' : IDL.Bool,
    'price' : IDL.Float64,
    'prepTimeMinutes' : IDL.Nat,
  });
  const Vendor = IDL.Record({
    'id' : VendorId,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'gateEntry' : IDL.Text,
    'platformNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCredits' : IDL.Func([IDL.Float64], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Text, VendorId, IDL.Text, IDL.Float64, IDL.Bool, IDL.Nat],
        [MenuId],
        [],
      ),
    'addVendor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [VendorId], []),
    'applyReferral' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([OrderId], [], []),
    'deductCredits' : IDL.Func([IDL.Float64], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([OrderId], [OrderType], ['query']),
    'getOrdersByUser' : IDL.Func([UserId], [IDL.Vec(OrderType)], ['query']),
    'getOrdersByVendor' : IDL.Func([VendorId], [IDL.Vec(OrderType)], ['query']),
    'getPNRHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUser' : IDL.Func([UserId], [User], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'listMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'listVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'placeOrder' : IDL.Func(
        [
          UserId,
          VendorId,
          IDL.Vec(
            IDL.Record({
              'quantity' : IDL.Nat,
              'price' : IDL.Float64,
              'menuItemId' : IDL.Text,
            })
          ),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [OrderId],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text, Phone], [], []),
    'storePNR' : IDL.Func([IDL.Text], [], []),
    'toggleItemAvailability' : IDL.Func([MenuId], [], []),
    'updateMenuItem' : IDL.Func(
        [
          MenuId,
          IDL.Text,
          VendorId,
          IDL.Text,
          IDL.Float64,
          IDL.Bool,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateVendor' : IDL.Func(
        [VendorId, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };