/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type MenuId = bigint;
export type UserId = Principal;
export interface MenuItem {
    id: MenuId;
    categoryName: string;
    name: string;
    isAvailable: boolean;
    vendorId: VendorId;
    rating: number;
    isVeg: boolean;
    price: number;
    prepTimeMinutes: bigint;
}
export interface User {
    id: UserId;
    referralCode: string;
    isBNPLEnabled: boolean;
    name: string;
    pnrHistory: Array<string>;
    phone: Phone;
    walletCredits: number;
    isVerifiedTraveler: boolean;
    seatNumber: string;
    coachNumber: string;
}
export type Phone = string;
export interface Vendor {
    id: VendorId;
    name: string;
    isActive: boolean;
    gateEntry: string;
    platformNumber: string;
}
export type VendorId = bigint;
export interface OrderType {
    id: OrderId;
    status: string;
    paymentMethod: string;
    trainNumber: string;
    userId: Principal;
    createdAt: bigint;
    totalAmount: number;
    vendorId: VendorId;
    discount: number;
    ecoPackaging: boolean;
    items: Array<{
        quantity: bigint;
        price: number;
        menuItemId: string;
    }>;
    seatNumber: string;
    subtotal: number;
    coachNumber: string;
    platformNumber: string;
}
export type OrderId = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCredits(amount: number): Promise<void>;
    addMenuItem(name: string, vendorId: VendorId, categoryName: string, price: number, isVeg: boolean, prepTimeMinutes: bigint): Promise<MenuId>;
    addVendor(name: string, platformNumber: string, gateEntry: string): Promise<VendorId>;
    applyReferral(referralCode: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelOrder(orderId: OrderId): Promise<void>;
    deductCredits(amount: number): Promise<void>;
    getAllOrders(): Promise<Array<OrderType>>;
    getCallerUserRole(): Promise<UserRole>;
    getOrder(orderId: OrderId): Promise<OrderType>;
    getOrdersByUser(userId: UserId): Promise<Array<OrderType>>;
    getOrdersByVendor(vendorId: VendorId): Promise<Array<OrderType>>;
    getPNRHistory(): Promise<Array<string>>;
    getUser(user: UserId): Promise<User>;
    isCallerAdmin(): Promise<boolean>;
    listMenuItems(): Promise<Array<MenuItem>>;
    listMenuItemsByCategory(category: string): Promise<Array<MenuItem>>;
    listVendors(): Promise<Array<Vendor>>;
    placeOrder(userId: UserId, vendorId: VendorId, items: Array<{
        quantity: bigint;
        price: number;
        menuItemId: string;
    }>, paymentMethod: string, coachNumber: string, seatNumber: string, platformNumber: string, trainNumber: string, ecoPackaging: boolean): Promise<OrderId>;
    registerUser(name: string, phone: Phone): Promise<void>;
    storePNR(pnr: string): Promise<void>;
    toggleItemAvailability(id: MenuId): Promise<void>;
    updateMenuItem(id: MenuId, name: string, vendorId: VendorId, categoryName: string, price: number, isVeg: boolean, prepTimeMinutes: bigint, isAvailable: boolean): Promise<void>;
    updateOrderStatus(orderId: OrderId, newStatus: string): Promise<void>;
    updateProfile(coachNumber: string, seatNumber: string): Promise<void>;
    updateVendor(id: VendorId, name: string, platformNumber: string, gateEntry: string, isActive: boolean): Promise<void>;
}
import type { UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCredits(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCredits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCredits(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: string, arg1: VendorId, arg2: string, arg3: number, arg4: boolean, arg5: bigint): Promise<MenuId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addVendor(arg0: string, arg1: string, arg2: string): Promise<VendorId> {
        if (this.processError) {
            try {
                const result = await this.actor.addVendor(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVendor(arg0, arg1, arg2);
            return result;
        }
    }
    async applyReferral(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyReferral(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyReferral(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelOrder(arg0: OrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async deductCredits(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deductCredits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductCredits(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<OrderType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<OrderType> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return result;
        }
    }
    async getOrdersByUser(arg0: UserId): Promise<Array<OrderType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByUser(arg0);
            return result;
        }
    }
    async getOrdersByVendor(arg0: VendorId): Promise<Array<OrderType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByVendor(arg0);
            return result;
        }
    }
    async getPNRHistory(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPNRHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPNRHistory();
            return result;
        }
    }
    async getUser(arg0: UserId): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMenuItems();
            return result;
        }
    }
    async listMenuItemsByCategory(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMenuItemsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMenuItemsByCategory(arg0);
            return result;
        }
    }
    async listVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVendors();
            return result;
        }
    }
    async placeOrder(arg0: UserId, arg1: VendorId, arg2: Array<{
        quantity: bigint;
        price: number;
        menuItemId: string;
    }>, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: boolean): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: Phone): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async storePNR(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storePNR(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePNR(arg0);
            return result;
        }
    }
    async toggleItemAvailability(arg0: MenuId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleItemAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleItemAvailability(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuId, arg1: string, arg2: VendorId, arg3: string, arg4: number, arg5: boolean, arg6: bigint, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return result;
        }
    }
    async updateVendor(arg0: VendorId, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
